spring.application.name=veeb
server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7ur7mm7r5hc73bd62jg-a.oregon-postgres.render.com/projekt_database_xek5
spring.datasource.username=projekt_user
spring.datasource.password=AfQ9KqF1F7zMcNpR5cmYm7awZWjXhSJj